name: Query User

on:
  workflow_dispatch:

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh query api
      run: |
        gh api graphql -F owner='{owner}' --paginate -f query='
          query($owner: String!, $endCursor: String) {
            user(login: $owner) {
              contributionsCollection {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions 
                totalRepositoryContributions
                restrictedContributionsCount 
                totalPullRequestReviewContributions 
              }
              followers {
                totalCount
              }
              issues {
                totalCount
              }
              pullRequests {
                totalCount
              }
              repositories(first: 100, after: $endCursor, ownerAffiliations: OWNER, isFork: false) {
                totalCount
                nodes {
                  stargazerCount 
                  forkCount
                  watchers {
                    totalCount
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }              
              repositoriesContributedTo {
                totalCount
              }
            }
          }
        '
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    #- name: gh query api
      #run: |
        #curl \
        #  -H "Accept: application/vnd.github.cloak-preview+json" \
        #  -G https://api.github.com/search/commits?q=author:cicirello+total_count
        #gh api search/commits -X GET -H "Accept: application/vnd.github.cloak-preview+json" -f q='committer:{owner} {owner}'
      #env:
        #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
