name: Query User

on:
  workflow_dispatch:

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh api query various user stats
      run: |
        gh api graphql -F owner='{owner}' --paginate -f query='
          query($owner: String!, $endCursor: String) {
            user(login: $owner) {
              contributionsCollection {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              followers {
                totalCount
              }
              issues {
                totalCount
              }
              pullRequests {
                totalCount
              }
              repositoriesContributedTo {
                totalCount
              }
              watching(ownerAffiliations: OWNER) {
                totalCount
              }
              repositories(first: 100, after: $endCursor, ownerAffiliations: OWNER, isFork: false) {
                totalCount
                nodes {
                  stargazerCount 
                  forkCount
                  isArchived
                  isFork
                  isPrivate
                  watchers {
                    totalCount
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }              
            }
          }
        '
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: gh api query contributions for various years
      run: |
        gh api graphql -F owner='{owner}' -f query='
          query($owner: String!) {
            user(login: $owner) {
              contributionsCollection(from: "2009-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2010-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2011-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2012-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2013-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2014-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2015-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2016-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2017-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2018-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2019-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2020-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
              contributionsCollection(from: "2021-01-01T00:00:00.001Z") {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions
                totalPullRequestReviewContributions
                totalRepositoryContributions
                restrictedContributionsCount 
              }
            }
          }
        '
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    #- name: gh query api
      #run: |
        #curl \
        #  -H "Accept: application/vnd.github.cloak-preview+json" \
        #  -G https://api.github.com/search/commits?q=author:cicirello+total_count
        #gh api search/commits -X GET -H "Accept: application/vnd.github.cloak-preview+json" -f q='author:{owner}' -f sort=author-date -f order=desc -f page=1 -f per_page=1
      #env:
        #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
