name: Query User

on:
  workflow_dispatch:

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - name: gh query api
      run: |
        gh api graphql -f query='
          query() {
            viewer {
              contributionsCollection {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions 
                totalRepositoryContributions 
             }
             followers {
               totalCount
             }
             gists {
               totalCount
             }
             repositoriesContributedTo {
               totalCount
             }
          }
        }
      '
