name: Query User

on:
  workflow_dispatch:

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh query api
      run: |
        gh api graphql -F owner='{owner}' -f query='
          query($owner: String!) {
            user(login: $owner) {
              contributionsCollection {
                totalCommitContributions 
                totalIssueContributions 
                totalPullRequestContributions 
                totalRepositoryContributions 
              }
              followers {
                totalCount
              }
              repositoriesContributedTo {
                totalCount
              }
            }
          }
        '
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
