name: Code Query

on:
  workflow_dispatch:
    inputs:
      USER:
        description: 'The user to query'
        required: true
      ACTION:
        description: 'The repo'
        required: true

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: gh api query code search
      run: |
        gh search code "${{ github.event.inputs.USER }}/${{ github.event.inputs.ACTION }}" "path:.github/workflows" --language YAML --json repository
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
