name: Code Query

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'The user to query'
        required: true
      repo:
        description: 'The repo'
        required: true

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh api query code search
      run: |
        gh api search/code -f q='cicirello+jacoco-badge-generator+path%3A.github/workflows+language%3AYAML' -f type=Code
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
