name: Code Query

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'The user to query'
        required: true
      repo:
        description: 'The repo'
        required: true

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh api query code search
      run: |
        gh api -H 'Accept: application/vnd.github.v3+json' -X GET 'search/code'  -f q='cicirello'
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
