name: Convert

on:
  workflow_dispatch:
    inputs:
      ORIGINAL:
        description: 'File to convert'
        required: true
      WIDTH:
        description: 'target width'
        required: true
      HEIGHT:
        description: 'target height'
        required: true

jobs:
  convert:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Convert
      run: |
        npm install svg2png -g
        svg2png ${{ github.event.inputs.ORIGINAL }} --width=${{ github.event.inputs.WIDTH }} --height=${{ github.event.inputs.HEIGHT }}
    
    - name: Commit and push 
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit it'
        add: '*.png'
 
