name: Docker Code Query

on:
  workflow_dispatch:
    inputs:
      USER:
        description: 'The user to query'
        required: true
      ACTION:
        description: 'The repo'
        required: true

jobs:
  query:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: gh api query code search
      run: |
        gh api search/code?q=${{ github.event.inputs.USER }}+${{ github.event.inputs.ACTION }}+path%3A.github%2Fworkflows+language%3ADockerfile&per_page=1&page=1
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
