  
name: user-statistician

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Generate the user stats image
      uses: cicirello/user-statistician@language-exclude-repos
      with:
        colors: dark
        language-repository-exclusions: cicirello.github.io
        hide-keys: general, repositories, contributions
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
